# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeopsyCollect
                                 A QGIS plugin
 This plugin fetches geometrical data from the GeoPsy Collect platform and visualizes it as points, polylines or polygons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-08-12
        git sha              : $Format:%H$
        copyright            : (C) 2022 by David Kitavi
        email                : daviskitavi@geopsyresearch.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from fileinput import filename
import sys
import json
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QUrl
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject, Qgis, QgsNetworkAccessManager, QgsSettings, QgsNetworkRequestParameters
from qgis.PyQt.QtNetwork import QNetworkRequest
import requests
import qgis
from qgis.core import QgsVectorLayer, QgsFeature, QgsPoint


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .geopsy_collect_dialog import GeopsyCollectDialog
import os.path


class GeopsyCollect:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeopsyCollect_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GeoPsy Collect')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GeopsyCollect', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/geopsy_collect/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Link GeoPsy Collect'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&GeoPsy Collect'),
                action)
            self.iface.removeToolBarIcon(action)

    def login(self):
        """Gets user credentials and logs in to the site"""
        self.username = self.dlg.username.toPlainText()
        self.password = self.dlg.password.text()

        validInput = self.inputCheck()

        if validInput:
            self.fetchForms()


    def inputCheck(self):
        if(self.username == ""):
            self.iface.messageBar().pushMessage(
                "Error", "Your email address is blank", level=Qgis.Critical
            )
            return False

        if(self.password == ""):
            self.iface.messageBar().pushMessage(
                "Error", "Your password is blank", level=Qgis.Critical
            )
            return False

        return True


    def fetchForms(self):
        url = "http://127.0.0.1:3000/api/login"
        params = {
            "username": self.username,
            "password": self.password
        }

        req = QNetworkRequest(QUrl(url))
        req.setAttribute(QNetworkRequest.Attribute(QgsNetworkRequestParameters.AttributeInitiatorClass), "QgsPluginInstaller")
        req.setAttribute(QNetworkRequest.Attribute(QgsNetworkRequestParameters.AttributeInitiatorRequestId), "sendVote")
        req.setRawHeader(b"Content-Type", b"application/json")
        self.r = QgsNetworkAccessManager.instance().post(req, bytes(json.dumps(params), "utf-8"))
        self.r.finished.connect(self.handleDone)

    def handleDone(self):
        responseData = self.r.readAll()
        data = str(responseData.data(), encoding='utf-8')

        if data == 'Invalid username or password':

            self.iface.messageBar().pushMessage(
                "Error", "The user does not exist", level=Qgis.Critical
            )

            return False

        else:
            #jsonData = json.loads(data)
            params = {
                "username": self.username
            }

            req = QNetworkRequest(QUrl("http://127.0.0.1:3000/api/fetchUserForms"))
            req.setAttribute(QNetworkRequest.Attribute(QgsNetworkRequestParameters.AttributeInitiatorClass), "QgsPluginInstaller")
            req.setAttribute(QNetworkRequest.Attribute(QgsNetworkRequestParameters.AttributeInitiatorRequestId), "sendVote")
            req.setRawHeader(b"Content-Type", b"application/json")
            self.reply = QgsNetworkAccessManager.instance().post(req, bytes(json.dumps(params), "utf-8"))
            self.reply.finished.connect(self.handleDone2)


    def handleDone2(self):
        forms = self.reply.readAll()
        formsAsString = str(forms.data(), encoding='utf-8')
        obj = json.loads(formsAsString)
        self.formsObj = obj['forms']
        data = []
        for form in self.formsObj:
            data.append(form["title"])

        self.dlg.forms.addItems(data)

        self.iface.messageBar().pushMessage(
            "Sucess", "The forms have been loaded", level=Qgis.Success, duration=60
        )


    def cancel(self):
        self.dlg.close()

    def apply(self):
        selectedFormIndex = self.dlg.forms.currentIndex()
        self.selectedForm = self.formsObj[selectedFormIndex]
        self.selectedFormId = self.selectedForm["form_id"]

        self.iface.messageBar().pushMessage(
            "Success", "You are viewing "+self.selectedFormId, level=Qgis.Success, duration=20
        )

        params = {
            "form_id": self.selectedFormId
        }

        req = QNetworkRequest(QUrl("http://127.0.0.1:3000/api/getresponse"))
        req.setAttribute(QNetworkRequest.Attribute(QgsNetworkRequestParameters.AttributeInitiatorClass), "QgsPluginInstaller")
        req.setAttribute(QNetworkRequest.Attribute(QgsNetworkRequestParameters.AttributeInitiatorRequestId), "sendVote")
        req.setRawHeader(b"Content-Type", b"application/json")
        self.response = QgsNetworkAccessManager.instance().post(req, bytes(json.dumps(params), "utf-8"))
        self.response.finished.connect(self.handleDone3)

    def handleDone3(self):
        response = self.response.readAll()
        responseAsString = str(response.data(), encoding='utf-8')
        self.iface.messageBar().pushMessage(
            "Success", responseAsString, level=Qgis.Success, duration=60
        )
        res = json.loads(responseAsString)
        resObj = res["response"]

        pointData = []
        lineData = []
        polygonData = []

        for data in resObj:
            realResponse = data["response"]
            for ress in realResponse:
                if ress["questionType"] == 'Point':
                    pointData.append(ress["response"])

                elif ress["questionType"] == 'Polyline':
                    lineData.append(ress["response"])

                elif ress["questionType"] == 'Polygon':
                    polygonData.append(ress["response"])

                else:
                    continue



    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = GeopsyCollectDialog()
            self.dlg.login.clicked.connect(self.login)
            self.dlg.cancel.clicked.connect(self.cancel)
            self.dlg.load.clicked.connect(self.apply)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
